const API='https://heckakjcpwomoucobtau.supabase.co/functions/v1/diretoria-crm-api';
const SESSION_KEY='diretoria_hml_session';
let sessionValue=localStorage.getItem(SESSION_KEY)||'';
let selectedId=null;
let overview=null;
const $=id=>document.getElementById(id);
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function fmtDate(v){if(!v)return'—';return new Date(v).toLocaleString('pt-BR');}
function money(v){if(v===null||v===undefined)return'—';const n=Number(v);return Number.isFinite(n)?n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):String(v);}
async function api(path){const headers={Accept:'application/json'};if(sessionValue)headers.Authorization=`Bearer ${sessionValue}`;const res=await fetch(API+path,{headers,cache:'no-store'});const body=await res.json().catch(()=>({ok:false,code:'INVALID_RESPONSE'}));if(!res.ok){const e=new Error(body.code||`HTTP_${res.status}`);e.status=res.status;throw e;}return body;}
async function validate(){if(!sessionValue){location.replace('/');return false;}try{const h=await api('/health');$('session').textContent=`sessão até ${new Date(h.expiresAt).toLocaleString('pt-BR')}`;$('blocked').classList.add('hidden');$('app').classList.remove('hidden');return true;}catch{localStorage.removeItem(SESSION_KEY);location.replace('/');return false;}}
function renderOverview(data){overview=data;const t=data.total||{};$('metrics').innerHTML=[['Perfis',t.total||0],['Últimas 24h',t.last_24h||0],['Últimos 7 dias',t.last_7d||0],['Origens',data.sources?.length||0]].map(([a,b])=>`<div class="metric"><span>${esc(a)}</span><b>${esc(b)}</b></div>`).join('');$('stages').innerHTML=(data.stages||[]).map(s=>`<button class="stage-bar" data-stage="${esc(s.stage)}">${esc(s.stage)} · ${esc(s.count)}</button>`).join('');$('stages').querySelectorAll('button').forEach(b=>b.onclick=()=>{$('stage').value=b.dataset.stage==='sem_estagio'?'sem_estagio':b.dataset.stage;loadProfiles();});fillSelect('stage',(data.stages||[]).map(x=>x.stage));fillSelect('source',(data.sources||[]).map(x=>x.source));fillSelect('campaign',(data.campaigns||[]).map(x=>x.campaign));}
function fillSelect(id,values){const el=$(id),current=el.value,first=el.options[0]?.outerHTML||'';el.innerHTML=first+[...new Set(values.filter(Boolean))].map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');if([...el.options].some(o=>o.value===current))el.value=current;}
function consentChip(label,value){if(value===null||value===undefined)return'';return`<span class="chip ${value?'ok':'off'}">${esc(label)} ${value?'✓':'×'}</span>`;}
async function loadOverview(){try{renderOverview(await api('/overview'));}catch(e){if(e.status===401)return invalidate();$('metrics').innerHTML=`<div class="message">Falha no overview: ${esc(e.message)}</div>`;}}
function filters(){const p=new URLSearchParams();for(const [k,id] of [['search','search'],['stage','stage'],['source','source'],['campaign','campaign']]){const v=$(id).value.trim();if(v)p.set(k,v);}p.set('limit','75');return p.toString();}
async function loadProfiles(){const box=$('items');box.innerHTML='<div class="message">Carregando…</div>';try{const data=await api('/profiles?'+filters());const items=data.items||[];if(!items.length){box.innerHTML='<div class="message">Nenhum perfil neste filtro.</div>';return;}box.innerHTML=items.map(p=>`<button class="person ${p.id===selectedId?'active':''}" data-id="${esc(p.id)}"><strong>${esc(p.full_name)}</strong><div class="small">${esc(p.email_normalized||p.phone_e164||p.display_code)}</div><div class="chips"><span class="chip">${esc(p.stage)}</span>${p.source?`<span class="chip">${esc(p.source)}</span>`:''}${p.campaign?`<span class="chip">${esc(p.campaign)}</span>`:''}${consentChip('WA',p.whatsapp)}${consentChip('MKT',p.marketing)}</div></button>`).join('');box.querySelectorAll('.person').forEach(b=>b.onclick=()=>loadProfile(b.dataset.id));if(!selectedId&&items[0])await loadProfile(items[0].id);}catch(e){if(e.status===401)return invalidate();box.innerHTML=`<div class="message">Falha: ${esc(e.message)}</div>`;}}
function timeline(items,titleField,timeField,detail){if(!items?.length)return'<div class="message">Sem registros.</div>';return`<div class="timeline">${items.map(x=>`<div class="event"><b>${esc(x[titleField]||'registro')}</b><div>${esc(detail(x))}</div><div>${esc(fmtDate(x[timeField]))}</div></div>`).join('')}</div>`;}
function latestConsent(consents,type){return consents?.find(c=>c.consent_type===type);}
async function loadProfile(id){selectedId=id;document.querySelectorAll('.person').forEach(b=>b.classList.toggle('active',b.dataset.id===id));$('detail').innerHTML='<div class="message">Carregando perfil…</div>';try{const d=await api('/profiles/'+id);const p=d.profile;$('title').textContent=p.full_name;$('subtitle').textContent=`${p.display_code} · criado ${fmtDate(p.created_at)}`;const consentTypes=['privacy','marketing','whatsapp','email'];const cons=consentTypes.map(t=>{const c=latestConsent(d.consents,t);return`<div class="row"><span>${esc(t)}</span><strong>${c?c.granted?'SIM':'NÃO':'—'}</strong></div>`;}).join('');const payments=(d.payments||[]).map(x=>`<div class="row"><span>${esc(x.status)} · ${esc(x.purpose)}</span><strong>${money(x.amount_gross)}</strong></div>`).join('')||'<div class="message">Sem pagamentos.</div>';const credits=(d.credits||[]).map(x=>`<div class="row"><span>${esc(x.status)}</span><strong>${money(x.protected_value)}</strong></div>`).join('')||'<div class="message">Sem créditos.</div>';$('detail').innerHTML=`<div class="detail-grid"><section class="section"><h3>Identidade</h3><div class="rows"><div class="row"><span>E-mail</span><strong>${esc(p.email_normalized||'—')}</strong></div><div class="row"><span>Telefone</span><strong>${esc(p.phone_e164||'—')}</strong></div><div class="row"><span>Origem inicial</span><strong>${esc(p.first_source||'—')}</strong></div><div class="row"><span>Campanha inicial</span><strong>${esc(p.first_campaign||'—')}</strong></div></div></section><section class="section"><h3>Consentimentos atuais</h3><div class="rows">${cons}</div></section><section class="section"><h3>Lifecycle</h3>${timeline(d.stages,'to_stage','changed_at',x=>`${x.from_stage||'início'} → ${x.to_stage} · ${x.reason||''}`)}</section><section class="section"><h3>Atribuição</h3>${timeline(d.attributions,'source','occurred_at',x=>`${x.medium||'—'} · ${x.campaign||'sem campanha'} · ${x.referral_code||'sem referral'}`)}</section><section class="section"><h3>Interações</h3>${timeline(d.interactions,'interaction_type','occurred_at',x=>`${x.channel} · ${x.direction} · ${x.summary}`)}</section><section class="section"><h3>Analytics</h3>${timeline(d.analytics,'event_name','occurred_at',x=>JSON.stringify(x.properties||{}).slice(0,180))}</section><section class="section"><h3>Pagamentos</h3><div class="rows">${payments}</div></section><section class="section"><h3>Créditos</h3><div class="rows">${credits}</div></section><section class="section full"><h3>Auditoria</h3>${timeline(d.audit,'action','occurred_at',x=>`${x.entity_type} · ${x.reason||''}`)}</section></div>`;if(window.gsap)gsap.fromTo('#detail',{opacity:.4,y:4},{opacity:1,y:0,duration:.22});}catch(e){if(e.status===401)return invalidate();$('detail').innerHTML=`<div class="message">Falha ao carregar: ${esc(e.message)}</div>`;}}
function invalidate(){localStorage.removeItem(SESSION_KEY);location.replace('/');}
let debounce;for(const id of ['search','stage','source','campaign'])$(id).addEventListener(id==='search'?'input':'change',()=>{clearTimeout(debounce);debounce=setTimeout(()=>{selectedId=null;loadProfiles();},id==='search'?300:0);});$('refresh').onclick=async()=>{selectedId=null;await Promise.all([loadOverview(),loadProfiles()]);};
(async()=>{if(await validate()){await loadOverview();await loadProfiles();}})();
