const API='https://heckakjcpwomoucobtau.supabase.co/functions/v1/diretoria-pre-ad-api';
const SESSION_KEY='diretoria_hml_session';
let sessionValue=localStorage.getItem(SESSION_KEY)||'';
let selectedAsset=null;
let lastAssets=[];
const $=id=>document.getElementById(id);
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function n(v){return Number(v||0).toLocaleString('pt-BR');}
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(sessionValue)headers.Authorization=`Bearer ${sessionValue}`;const r=await fetch(API+path,{...options,headers,cache:'no-store'});const b=await r.json().catch(()=>({ok:false,code:'INVALID_RESPONSE'}));if(!r.ok){const e=new Error(b.code||`HTTP_${r.status}`);e.status=r.status;throw e;}return b;}
async function validate(){if(!sessionValue){location.replace('/');return false;}try{const h=await api('/health');$('session').textContent=`sessão até ${new Date(h.expiresAt).toLocaleString('pt-BR')} · pixels ${h.pixels}`;$('blocked').classList.add('hidden');$('app').classList.remove('hidden');return true;}catch{localStorage.removeItem(SESSION_KEY);location.replace('/');return false;}}
function renderRows(id,items,label,value){const el=$(id);el.innerHTML=items.length?items.map(x=>`<div class="row"><span>${esc(label(x))}</span><strong>${esc(value(x))}</strong></div>`).join(''):'<div class="muted">Sem dados.</div>';}
async function loadInsights(){const days=Number($('range').value);try{const d=await api(`/insights?days=${days}`),t=d.totals||{};$('metrics').innerHTML=[['Leads no período',t.leads||0],['Últimas 24h',t.last_24h||0],['Últimos 7 dias',t.last_7d||0],['Buckets rate-limit 24h',d.rateLimit24h?.buckets||0]].map(([a,b])=>`<div class="metric"><span>${esc(a)}</span><b>${esc(n(b))}</b></div>`).join('');renderRows('sources',d.sources||[],x=>`${x.source} · ${x.people} pessoa(s)`,x=>`${x.leads} atribuição(ões)`);renderRows('campaigns',d.campaigns||[],x=>`${x.campaign} · ${x.people} pessoa(s)`,x=>`${x.leads}`);renderRows('consents',d.consents||[],x=>x.consent_type,x=>`${x.granted}/${x.total} · ${x.granted_pct??0}%`);$('rate').textContent=`${n(d.rateLimit24h?.hits||0)} hit(s) em ${n(d.rateLimit24h?.buckets||0)} bucket(s). Último: ${d.rateLimit24h?.last_hit_at?new Date(d.rateLimit24h.last_hit_at).toLocaleString('pt-BR'):'—'}`;}catch(e){if(e.status===401)return invalidate();$('metrics').innerHTML=`<div class="message error">Falha nos insights: ${esc(e.message)}</div>`;}}
function assetQuery(){const p=new URLSearchParams();if($('rightsFilter').value)p.set('rightsStatus',$('rightsFilter').value);if($('usageFilter').value)p.set('usagePermission',$('usageFilter').value);if($('assetSearch').value.trim())p.set('search',$('assetSearch').value.trim());p.set('limit','150');return p.toString();}
function chip(v,ok=false){return`<span class="chip ${ok?'ok':'warn'}">${esc(v)}</span>`;}
async function loadAssets(){try{const d=await api('/assets?'+assetQuery());lastAssets=d.items||[];$('assets').innerHTML=lastAssets.length?lastAssets.map(a=>`<button class="asset ${a.id===selectedAsset?'active':''}" data-id="${esc(a.id)}"><strong>${esc(a.title||a.storage_key)}</strong><div class="small">${esc(a.historical_event_label||a.asset_type)} · ${esc(a.storage_key)}</div><div class="chips">${chip(a.rights_status,a.rights_status==='cleared')}${chip(a.usage_permission,a.usage_permission==='paid'||a.usage_permission==='unrestricted')}${(a.tags||[]).slice(0,4).map(t=>chip(t)).join('')}</div></button>`).join(''):'<div class="muted">Nenhum item catalogado.</div>';$('assets').querySelectorAll('.asset').forEach(b=>b.onclick=()=>selectAsset(b.dataset.id));}catch(e){if(e.status===401)return invalidate();$('assets').innerHTML=`<div class="message error">${esc(e.message)}</div>`;}}
function setForm(a){const f=$('assetForm'),set=(name,value)=>{if(f.elements[name])f.elements[name].value=value??'';};set('id',a?.id);set('assetType',a?.asset_type||'photo');set('storageKey',a?.storage_key);set('historicalEventLabel',a?.historical_event_label);set('capturedAt',a?.captured_at?new Date(a.captured_at).toISOString().slice(0,16):'');set('title',a?.title);set('description',a?.description);set('format',a?.format);set('quality',a?.quality);set('usagePermission',a?.usage_permission||'unknown');set('rightsStatus',a?.rights_status||'review_required');set('sourceCredit',a?.source_credit);set('externalSourceUrl',a?.external_source_url);set('rightsNotes',a?.rights_notes);set('tags',(a?.tags||[]).join(', '));$('assetMessage').textContent=a?`Editando ${a.id}. Mudanças de direitos serão auditadas.`:'Novo item. Sem upload de arquivo neste slice.';$('assetMessage').className='message';}
function selectAsset(id){selectedAsset=id;document.querySelectorAll('.asset').forEach(b=>b.classList.toggle('active',b.dataset.id===id));setForm(lastAssets.find(a=>a.id===id));}
function invalidate(){localStorage.removeItem(SESSION_KEY);location.replace('/');}
$('range').onchange=loadInsights;$('rightsFilter').onchange=loadAssets;$('usageFilter').onchange=loadAssets;let timer;$('assetSearch').oninput=()=>{clearTimeout(timer);timer=setTimeout(loadAssets,250);};$('newAsset').onclick=()=>{selectedAsset=null;setForm(null);};
$('assetForm').onsubmit=async ev=>{ev.preventDefault();const fd=new FormData(ev.currentTarget),id=String(fd.get('id')||'').trim();const payload={assetType:String(fd.get('assetType')||''),storageKey:String(fd.get('storageKey')||''),historicalEventLabel:String(fd.get('historicalEventLabel')||'')||undefined,capturedAt:String(fd.get('capturedAt')||'')?new Date(String(fd.get('capturedAt'))).toISOString():undefined,title:String(fd.get('title')||'')||undefined,description:String(fd.get('description')||'')||undefined,format:String(fd.get('format')||'')||undefined,quality:String(fd.get('quality')||'')||undefined,usagePermission:String(fd.get('usagePermission')||'unknown'),rightsStatus:String(fd.get('rightsStatus')||'review_required'),sourceCredit:String(fd.get('sourceCredit')||'')||undefined,externalSourceUrl:String(fd.get('externalSourceUrl')||'')||undefined,rightsNotes:String(fd.get('rightsNotes')||'')||undefined,tags:String(fd.get('tags')||'').split(',').map(x=>x.trim()).filter(Boolean)};const m=$('assetMessage');try{const r=await api(id?`/assets/${id}`:'/assets',{method:'POST',body:JSON.stringify(payload)});selectedAsset=id||r.assetId;m.textContent=id?'Metadados atualizados e auditados.':'Item criado e auditado.';m.className='message ok';await loadAssets();await loadInsights();if(selectedAsset)selectAsset(selectedAsset);}catch(e){m.textContent=`Falha: ${e.message}`;m.className='message error';}};
(async()=>{if(await validate()){await Promise.all([loadInsights(),loadAssets()]);setForm(null);}})();
