const READ='https://heckakjcpwomoucobtau.supabase.co/functions/v1/diretoria-admin-api';
const WRITE='https://heckakjcpwomoucobtau.supabase.co/functions/v1/diretoria-admin-write-api';
const SESSION_KEY='diretoria_hml_session';
let sessionValue=localStorage.getItem(SESSION_KEY)||'';
let selectedId=null;
let current=null;
let lastPaymentId=localStorage.getItem('diretoria_hml_last_payment')||'';
const $=id=>document.getElementById(id);
const NEXT={PLANEJAMENTO:'REATIVACAO',REATIVACAO:'LISTA_DE_ESPERA',LISTA_DE_ESPERA:'FORMACAO',FORMACAO:'QUORUM_EM_ANDAMENTO',CONFIRMADO:'VENDA_PUBLICA',VENDA_PUBLICA:'PRE_EVENTO',PRE_EVENTO:'AO_VIVO',AO_VIVO:'FECHAMENTO',FECHAMENTO:'ENCERRADO',ENCERRADO:'RETENCAO',RETENCAO:'PLANEJAMENTO'};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function money(v){if(v===null||v===undefined||v==='')return'—';const n=Number(v);return Number.isFinite(n)?n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):String(v);}
function toCents(value){let s=String(value??'').trim().replace(/\s|R\$/gi,'');if(!s)throw new Error('Valor obrigatório');if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.');else s=s.replace(',','.');if(!/^\d+(?:\.\d{1,2})?$/.test(s))throw new Error('Valor monetário inválido');const [w,f='']=s.split('.');return (BigInt(w)*100n+BigInt((f+'00').slice(0,2))).toString();}
function toBps(value){const s=String(value??'').trim().replace(',','.');if(!/^\d+(?:\.\d{1,2})?$/.test(s))throw new Error('Percentual inválido');const [w,f='']=s.split('.');return Number(w)*100+Number((f+'00').slice(0,2));}
function fields(form){return Object.fromEntries(new FormData(form).entries());}
function message(text,type=''){const el=$('message');el.textContent=text;el.className='message'+(type?' '+type:'');if(window.gsap)gsap.fromTo(el,{opacity:.35,y:3},{opacity:1,y:0,duration:.22});}
async function request(base,path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(sessionValue)headers.Authorization=`Bearer ${sessionValue}`;const res=await fetch(base+path,{...options,headers});const body=await res.json().catch(()=>({ok:false,code:'INVALID_RESPONSE'}));if(!res.ok){const e=new Error(body.code||`HTTP_${res.status}`);e.status=res.status;throw e;}return body;}
const read=path=>request(READ,path);
const write=(path,payload={})=>request(WRITE,path,{method:'POST',body:JSON.stringify(payload)});
async function validate(){if(!sessionValue){location.replace('/');return false;}try{const me=await read('/me');if(!me.allowed)throw new Error('NOT_ALLOWED');$('sessionState').textContent=`sessão ativa até ${new Date(me.expiresAt).toLocaleString('pt-BR')}`;$('blocked').classList.add('hidden');$('app').classList.remove('hidden');return true;}catch{localStorage.removeItem(SESSION_KEY);location.replace('/');return false;}}
function renderMetrics(q){const el=$('metrics');if(!q){el.classList.add('hidden');return;}const items=[['Capital protegido',money(q.protected_capital)],['Necessidade',money(q.financial_need)],['Membros',q.valid_credit_count??0],['Quórum mínimo',q.quorum_minimum??0]];el.innerHTML=items.map(([a,b])=>`<div class="metric"><span class="small">${esc(a)}</span><b>${esc(b)}</b></div>`).join('');el.classList.remove('hidden');}
async function loadEvents(){const box=$('events');box.innerHTML='<div class="empty">Carregando…</div>';try{const data=await read('/events');const list=data.events||[];if(!list.length){box.innerHTML='<div class="empty">Nenhuma edição HML.</div>';return;}box.innerHTML=list.map(e=>`<button class="event ${e.id===selectedId?'active':''}" data-id="${esc(e.id)}"><strong>${esc(e.name)}</strong><span class="small">${esc(e.event_code)} · ${esc(e.status)}</span></button>`).join('');box.querySelectorAll('.event').forEach(b=>b.onclick=()=>selectEvent(b.dataset.id));if(!selectedId)await selectEvent(list[0].id);}catch(e){box.innerHTML=`<div class="message error">${esc(e.message)}</div>`;}}
async function selectEvent(id){selectedId=id;document.querySelectorAll('.event').forEach(b=>b.classList.toggle('active',b.dataset.id===id));try{current=await read(`/events/${id}/summary`);$('title').textContent=current.event.name;$('subtitle').textContent=`${current.event.event_code} · ${current.event.status}`;renderMetrics(current.quorum);$('actions').classList.remove('hidden');const next=NEXT[current.event.status];$('advance').disabled=!next;$('advance').textContent=next?`Avançar para ${next}`:(current.event.status==='QUORUM_EM_ANDAMENTO'?'Aguardando viabilidade financeira':current.event.status==='VIAVEL'?'Use o gate de confirmação':'Sem avanço manual neste estado');message(`Resumo carregado. Estado financeiro: ${current.quorum?.financial_status||'sem snapshot'}.`);}catch(e){message(`Falha ao carregar edição: ${e.message}`,'error');}}
async function refreshSelected(){await loadEvents();if(selectedId)await selectEvent(selectedId);}
$('refresh').onclick=refreshSelected;
$('recalc').onclick=async()=>{if(!selectedId)return;try{const r=await write(`/events/${selectedId}/recalculate`);message(`Quórum recalculado: ${r.quorum.status||r.quorum.financialStatus||'ok'}.`,'ok');await refreshSelected();}catch(e){message(e.message,'error');}};
$('newEvent').onclick=async()=>{const name=prompt('Nome da edição HML','Diretoria HML #01');if(!name)return;const code=prompt('Código','DIR-HML-001');if(!code)return;const slug=prompt('Slug','diretoria-hml-001');if(!slug)return;const capacity=Number(prompt('Capacidade estimada','700'));try{const r=await write('/events',{name,eventCode:code,slug,capacity});selectedId=r.event.id;message('Edição HML criada em PLANEJAMENTO.','ok');await refreshSelected();}catch(e){message(e.message,'error');}};
$('advance').onclick=async()=>{if(!current)return;const to=NEXT[current.event.status];if(!to)return;try{await write(`/events/${selectedId}/transition`,{to,reason:`Avanço controlado HML para ${to}`});message(`Edição avançou para ${to}.`,'ok');await refreshSelected();}catch(e){message(e.message,'error');}};
$('configForm').onsubmit=async ev=>{ev.preventDefault();const f=fields(ev.currentTarget);try{const contingency=f.contingencyType==='fixed'?{type:'fixed',amountCents:toCents(f.contingency)}:{type:'percentage',basisPoints:toBps(f.contingency)};await write(`/events/${selectedId}/financial-config`,{founderTicketGrossCents:toCents(f.ticket),estimatedFeePerMemberCents:toCents(f.fee),variableCostPerMemberCents:toCents(f.variable),approvedExposureLimitCents:toCents(f.exposure),contingency});message('Nova versão financeira criada.','ok');await refreshSelected();}catch(e){message(e.message,'error');}};
$('costForm').onsubmit=async ev=>{ev.preventDefault();const f=fields(ev.currentTarget);try{await write(`/events/${selectedId}/costs`,{category:f.category,description:f.description,costType:f.costType,amountCents:toCents(f.amount)});message('Custo protegido aprovado.','ok');await refreshSelected();}catch(e){message(e.message,'error');}};
$('revenueForm').onsubmit=async ev=>{ev.preventDefault();const f=fields(ev.currentTarget);try{await write(`/events/${selectedId}/guaranteed-revenues`,{revenueType:f.revenueType,status:f.status,counterparty:f.counterparty,grossAmountCents:toCents(f.gross),eligibleAmountCents:toCents(f.eligible)});message('Receita registrada.','ok');await refreshSelected();}catch(e){message(e.message,'error');}};
$('paymentForm').onsubmit=async ev=>{ev.preventDefault();const f=fields(ev.currentTarget);try{const r=await write(`/events/${selectedId}/mock-payments`,{amountGrossCents:toCents(f.amount)});lastPaymentId=r.payment.id;localStorage.setItem('diretoria_hml_last_payment',lastPaymentId);$('paymentState').textContent=`Último: ${lastPaymentId} · ${r.payment.status}`;message('Pagamento mock criado como PENDING.','ok');}catch(e){message(e.message,'error');}};
$('confirmPayment').onclick=async()=>{if(!lastPaymentId)return message('Crie um pagamento primeiro.','error');try{const r=await write(`/mock-payments/${lastPaymentId}/confirm`);message(`Pagamento confirmado. Crédito ${r.result.creditId}.`,'ok');await refreshSelected();}catch(e){message(e.message,'error');}};
$('refundPayment').onclick=async()=>{if(!lastPaymentId)return message('Nenhum pagamento selecionado.','error');if(!confirm('Reembolsar o último pagamento HML?'))return;try{await write(`/payments/${lastPaymentId}/refund`,{reason:'Reembolso controlado via console HML'});message('Pagamento reembolsado; capital protegido recalculado.','ok');await refreshSelected();}catch(e){message(e.message,'error');}};
$('checkForm').onsubmit=async ev=>{ev.preventDefault();const f=fields(ev.currentTarget);try{await write(`/events/${selectedId}/checks`,{code:f.code,label:f.label,status:f.status,required:true});message('Checklist atualizado.','ok');await refreshSelected();}catch(e){message(e.message,'error');}};
$('goForm').onsubmit=async ev=>{ev.preventDefault();const f=fields(ev.currentTarget);try{const r=await write(`/events/${selectedId}/go-no-go`,{projectedRequiredExposureCents:toCents(f.exposure)});message(`GO/NO-GO: ${r.review.result}${r.review.reasons?.length?' · '+r.review.reasons.join(', '):''}.`,r.review.result==='GO'?'ok':'error');await refreshSelected();}catch(e){message(e.message,'error');}};
$('confirmForm').onsubmit=async ev=>{ev.preventDefault();const f=fields(ev.currentTarget);if(!confirm('Confirmar esta edição somente no HML?'))return;try{await write(`/events/${selectedId}/confirm`,{reason:f.reason});message('Edição CONFIRMADA pelo gate server-side.','ok');await refreshSelected();}catch(e){message(e.message,'error');}};
(async()=>{if(await validate()){if(lastPaymentId)$('paymentState').textContent=`Último pagamento: ${lastPaymentId}`;await loadEvents();}})();
