const SUPABASE_URL='https://heckakjcpwomoucobtau.supabase.co';
const SUPABASE_PUBLISHABLE='sb_publishable_tqabW8ADQJRin-kDMmXGTw_MtCv-VUK';
const MEMBER_API='https://heckakjcpwomoucobtau.supabase.co/functions/v1/diretoria-member-api';
const client=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id);
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function money(v){if(v===null||v===undefined)return'—';const n=Number(v);return Number.isFinite(n)?n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):String(v);}
function msg(text,type=''){const el=$('authMessage');el.textContent=text;el.className='message'+(type?' '+type:'');}
function memberMsg(text,type=''){const el=$('memberMessage');el.textContent=text;el.className='message'+(type?' '+type:'');}
function pane(name){for(const p of ['login','signup','recovery']){$(p+'Pane').classList.toggle('hidden',p!==name);$(p+'Tab').classList.toggle('active',p===name);}}
for(const p of ['login','signup','recovery'])$(p+'Tab').onclick=()=>pane(p);
async function memberApi(path,options={}){const {data:{session}}=await client.auth.getSession();if(!session?.access_token)throw Object.assign(new Error('AUTH_REQUIRED'),{status:401});const r=await fetch(MEMBER_API+path,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`,...(options.headers||{})}});const body=await r.json().catch(()=>({ok:false,code:'INVALID_RESPONSE'}));if(!r.ok){const e=new Error(body.code||`HTTP_${r.status}`);e.status=r.status;e.body=body;throw e;}return body;}
async function bootstrapAndLoad(){const {data:{session}}=await client.auth.getSession();if(!session){showLoggedOut();return;}showLoggedIn(session.user);try{memberMsg('Vinculando identidade autenticada ao customer_id…');await memberApi('/account/bootstrap',{method:'POST',body:'{}'});const data=await memberApi('/wallet');renderWallet(data.wallet);memberMsg('Conta autenticada e carteira sincronizada.','ok');}catch(e){$('wallet').classList.add('hidden');const human={MEMBER_EMAIL_VERIFICATION_REQUIRED_FOR_LINK:'Este e-mail já existe na lista de espera. Confirme o e-mail antes de vincular a conta.',MEMBER_PHONE_VERIFICATION_REQUIRED_FOR_LINK:'Este telefone já existe. A verificação é obrigatória antes do vínculo.',MEMBER_IDENTITY_CONFLICT:'E-mail e telefone apontam para perfis diferentes. O vínculo foi bloqueado para revisão.',MEMBER_PROFILE_ALREADY_HAS_ACCOUNT:'Este perfil já possui outra conta autenticada.'}[e.message];memberMsg(human||`Não foi possível preparar a conta: ${e.message}`,'error');}}
function showLoggedOut(){$('loggedOut').classList.remove('hidden');$('loggedIn').classList.add('hidden');}
function showLoggedIn(user){$('loggedOut').classList.add('hidden');$('loggedIn').classList.remove('hidden');$('memberName').textContent=String(user.user_metadata?.full_name||user.email||'Minha Diretoria');$('memberMeta').textContent=`Auth HML · ${user.email||user.phone||user.id}`;}
function renderWallet(w){const a=w.account||{};$('memberName').textContent=a.full_name||'Minha Diretoria';$('memberMeta').innerHTML=`${esc(a.display_code)} · lifecycle <span class="pill">${esc(a.crm_stage||'lead')}</span> · perfil ${esc(a.profile_status)}`;const credits=w.credits||[];$('credits').innerHTML=credits.length?credits.map(c=>`<div class="row"><span>${esc(c.event_name)}<br><small>${esc(c.status)}</small></span><strong>${money(c.protected_value)}</strong></div>`).join(''):'<div class="muted">Nenhum crédito válido ou histórico.</div>';const payments=w.payments||[];$('payments').innerHTML=payments.length?payments.map(p=>`<div class="row"><span>${esc(p.status)}<br><small>${esc(p.payment_method)}</small></span><strong>${money(p.amount_gross)}</strong></div>`).join(''):'<div class="muted">Nenhum pagamento HML.</div>';const ticketsImplemented=w.ticketsImplemented===true;const ticketCount=Array.isArray(w.tickets)?w.tickets.length:0;$('ticketsStatus').textContent=ticketsImplemented?`Ticketing disponível: ${ticketCount} ingresso(s) retornado(s) pela API.`:'Ticketing ainda não foi implementado nesta fase. Nenhum QR é fabricado pela interface.';$('wallet').classList.remove('hidden');}
$('loginForm').onsubmit=async ev=>{ev.preventDefault();const f=new FormData(ev.currentTarget);msg('Autenticando…');const {error}=await client.auth.signInWithPassword({email:String(f.get('email')||'').trim(),password:String(f.get('password')||'')});if(error)return msg(error.message,'error');msg('Login concluído.','ok');await bootstrapAndLoad();};
$('signupForm').onsubmit=async ev=>{ev.preventDefault();const f=new FormData(ev.currentTarget);msg('Criando conta…');const {data,error}=await client.auth.signUp({email:String(f.get('email')||'').trim(),password:String(f.get('password')||''),options:{data:{full_name:String(f.get('name')||'').trim()},emailRedirectTo:`${location.origin}/account.html`}});if(error)return msg(error.message,'error');if(data.session){msg('Conta criada e autenticada.','ok');await bootstrapAndLoad();}else msg('Conta criada. Verifique o e-mail para concluir a autenticação e vincular a identidade.','ok');};
$('recoveryForm').onsubmit=async ev=>{ev.preventDefault();const email=String(new FormData(ev.currentTarget).get('email')||'').trim();msg('Solicitando recuperação…');const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}/account.html?recovery=1`});if(error)return msg(error.message,'error');msg('Se o e-mail existir, a recuperação foi enviada.','ok');};
$('newPasswordForm').onsubmit=async ev=>{ev.preventDefault();const password=String(new FormData(ev.currentTarget).get('password')||'');const {error}=await client.auth.updateUser({password});if(error)return msg(error.message,'error');msg('Senha atualizada.','ok');$('newPasswordForm').classList.add('hidden');await bootstrapAndLoad();};
$('logoutBtn').onclick=async()=>{await client.auth.signOut();showLoggedOut();$('wallet').classList.add('hidden');memberMsg('Sessão encerrada.');};
client.auth.onAuthStateChange(async(event,session)=>{if(event==='PASSWORD_RECOVERY'){pane('recovery');$('newPasswordForm').classList.remove('hidden');msg('Defina uma nova senha para concluir a recuperação.','ok');}if(event==='SIGNED_IN'&&session)await bootstrapAndLoad();if(event==='SIGNED_OUT')showLoggedOut();});
(async()=>{const {data:{session}}=await client.auth.getSession();if(session)await bootstrapAndLoad();else showLoggedOut();})();
