import pg from 'pg';
const { Pool } = pg;
type Queryable={query(text:string,values?:unknown[]):Promise<{rows:any[];rowCount?:number|null}>};
export class PostgresCheckoutStartGuard{
  private readonly pool:any;
  constructor(connectionString:string){if(!connectionString)throw new Error('DATABASE_URL_REQUIRED');this.pool=new Pool({connectionString,max:3,idleTimeoutMillis:5000,connectionTimeoutMillis:5000});}
  async close(){await this.pool.end();}
  private async transaction<T>(fn:(client:Queryable)=>Promise<T>):Promise<T>{const client=await this.pool.connect();try{await client.query('BEGIN');const out=await fn(client);await client.query('COMMIT');return out;}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}
  async claim(providerSubject:string,intentId:string):Promise<{replayed:boolean;status:string;providerSessionId:string|null}>{
    const subject=String(providerSubject??'').trim(),id=String(intentId??'').trim();if(!subject)throw new Error('PROVIDER_SUBJECT_REQUIRED');if(!/^[0-9a-f-]{36}$/i.test(id))throw new Error('CHECKOUT_INTENT_ID_INVALID');
    return this.transaction(async client=>{const result=await client.query(`select ci.id,ci.status,ci.provider_session_id,ci.reconciliation_status from checkout_intents ci join users u on u.profile_id=ci.profile_id and u.auth_provider='supabase' and u.provider_subject=$2 and u.status='active' where ci.id=$1 for update of ci`,[id,subject]);const intent=result.rows[0];if(!intent)throw new Error('CHECKOUT_INTENT_NOT_FOUND');if(intent.status==='pending'&&intent.provider_session_id)return{replayed:true,status:intent.status,providerSessionId:intent.provider_session_id};if(intent.status!=='ready')throw new Error(`CHECKOUT_INTENT_NOT_READY:${intent.status}`);if(intent.reconciliation_status==='required')throw new Error('CHECKOUT_RECONCILIATION_REQUIRED');if(intent.reconciliation_status==='pending')throw new Error('CHECKOUT_START_ALREADY_IN_PROGRESS');await client.query(`update checkout_intents set reconciliation_status='pending',provider_started_at=now(),provider_error_code=null,updated_at=now() where id=$1`,[id]);return{replayed:false,status:'ready',providerSessionId:null};});
  }
  async recordProviderSession(intentId:string,providerSessionId:string,expiresAt?:string|null):Promise<{replayed:boolean;providerSessionId:string}>{
    const id=String(intentId??'').trim(),session=String(providerSessionId??'').trim();if(!/^[0-9a-f-]{36}$/i.test(id))throw new Error('CHECKOUT_INTENT_ID_INVALID');if(!session)throw new Error('PROVIDER_SESSION_ID_REQUIRED');
    return this.transaction(async client=>{const result=await client.query(`select id,status,provider,provider_session_id,reconciliation_status from checkout_intents where id=$1 for update`,[id]);const intent=result.rows[0];if(!intent)throw new Error('CHECKOUT_INTENT_NOT_FOUND');if(intent.provider!=='asaas')throw new Error('CHECKOUT_PROVIDER_NOT_ASAAS');if(!['ready','pending'].includes(intent.status))throw new Error(`CHECKOUT_INTENT_NOT_STARTABLE:${intent.status}`);if(intent.provider_session_id){if(intent.provider_session_id!==session)throw new Error('CHECKOUT_PROVIDER_SESSION_CONFLICT');return{replayed:true,providerSessionId:session};}await client.query(`update checkout_intents set provider_session_id=$2,expires_at=coalesce($3,expires_at),provider_started_at=coalesce(provider_started_at,now()),updated_at=now() where id=$1`,[id,session,expiresAt??null]);return{replayed:false,providerSessionId:session};});
  }
  async releaseDefinitiveFailure(intentId:string,code:string){await this.pool.query(`update checkout_intents set reconciliation_status='not_required',provider_error_code=$2,updated_at=now() where id=$1 and status='ready' and reconciliation_status='pending' and provider_session_id is null`,[intentId,String(code||'ASAAS_DEFINITIVE_ERROR').slice(0,120)]);}
  async requireReconciliation(intentId:string,code:string){await this.pool.query(`update checkout_intents set reconciliation_status='required',provider_error_code=$2,updated_at=now() where id=$1 and status in('ready','pending')`,[intentId,String(code||'ASAAS_UNCERTAIN_ERROR').slice(0,120)]);}
}
