import { createSupabaseContext } from 'npm:@supabase/server@^1';
import { PostgresCrmRead } from 'https://raw.githubusercontent.com/squalmg/diretoria/18c0cb740f261ec22645a7c33c9cc68964ec6fef/packages/db/src/crm-read.ts';

const CANONICAL_ORIGIN='https://diretoria-hml.vercel.app';
const LOCAL_ORIGINS=new Set(['http://localhost:3100','http://127.0.0.1:3100']);
let reader:PostgresCrmRead|null=null;
function cors(req:Request):HeadersInit{const origin=req.headers.get('origin');return{'Access-Control-Allow-Origin':origin&&(origin===CANONICAL_ORIGIN||LOCAL_ORIGINS.has(origin))?origin:CANONICAL_ORIGIN,'Access-Control-Allow-Headers':'authorization,content-type','Access-Control-Allow-Methods':'GET,OPTIONS','Access-Control-Max-Age':'86400','Vary':'Origin','Cache-Control':'no-store'};}
function json(req:Request,body:unknown,status=200){return Response.json(body,{status,headers:cors(req)});}
function originAllowed(origin:string|null){return !origin||origin===CANONICAL_ORIGIN||LOCAL_ORIGINS.has(origin);}
function bearer(req:Request){const m=/^Bearer\s+(.+)$/i.exec(req.headers.get('authorization')??'');return m?.[1]?.trim()||null;}
async function sha256(value:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,'0')).join('');}
function routePath(req:Request){const p=new URL(req.url).pathname,marker='/diretoria-crm-api',i=p.indexOf(marker);return i<0?p:p.slice(i+marker.length)||'/';}
function crm(){if(reader)return reader;const connection=Deno.env.get('SUPABASE_DB_URL');if(!connection)throw new Error('DATABASE_URL_REQUIRED');reader=new PostgresCrmRead(connection);return reader;}
async function session(req:Request){const token=bearer(req);if(!token?.startsWith('hml_'))return{response:json(req,{ok:false,code:'HML_SESSION_REQUIRED'},401)}as const;const{data:ctx,error}=await createSupabaseContext(req,{auth:'none'});if(error||!ctx)return{response:json(req,{ok:false,code:'SERVICE_UNAVAILABLE'},503)}as const;const hash=await sha256(token),now=new Date().toISOString();const{data,error:q}=await ctx.supabaseAdmin.from('hml_admin_sessions').select('id,expires_at').eq('token_hash',hash).is('revoked_at',null).gt('expires_at',now).maybeSingle();if(q)return{response:json(req,{ok:false,code:'HML_SESSION_QUERY_FAILED'},500)}as const;if(!data)return{response:json(req,{ok:false,code:'HML_SESSION_INVALID'},401)}as const;return{expiresAt:data.expires_at as string}as const;}
function intParam(raw:string|null,fallback:number,min:number,max:number){if(raw===null)return fallback;const n=Number(raw);if(!Number.isInteger(n)||n<min||n>max)throw new Error('CRM_PAGINATION_INVALID');return n;}
function opt(raw:string|null,max:number){if(raw===null)return undefined;const t=raw.trim();if(!t)return undefined;if(t.length>max)throw new Error('CRM_FILTER_TOO_LONG');return t;}
Deno.serve(async(req:Request)=>{const origin=req.headers.get('origin');if(!originAllowed(origin))return json(req,{ok:false,code:'ORIGIN_NOT_ALLOWED'},403);if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});if(req.method!=='GET')return json(req,{ok:false,code:'METHOD_NOT_ALLOWED'},405);const auth=await session(req);if('response'in auth)return auth.response;const path=routePath(req);try{if(path==='/'||path==='/health')return json(req,{ok:await crm().health(),service:'diretoria-crm-api',environment:'hml',mode:'read-only',expiresAt:auth.expiresAt});if(path==='/overview')return json(req,{ok:true,...await crm().overview()});if(path==='/profiles'){const u=new URL(req.url);const result=await crm().listProfiles({search:opt(u.searchParams.get('search'),120),stage:opt(u.searchParams.get('stage'),40),source:opt(u.searchParams.get('source'),120),campaign:opt(u.searchParams.get('campaign'),180),limit:intParam(u.searchParams.get('limit'),50,1,100),offset:intParam(u.searchParams.get('offset'),0,0,100000)});return json(req,{ok:true,...result});}const match=/^\/profiles\/([0-9a-f-]{36})$/i.exec(path);if(match)return json(req,{ok:true,...await crm().profile360(match[1])});return json(req,{ok:false,code:'NOT_FOUND'},404);}catch(error){const raw=error instanceof Error?error.message:'CRM_QUERY_FAILED';if(raw==='PROFILE_NOT_FOUND')return json(req,{ok:false,code:raw},404);if(raw.includes('INVALID')||raw.includes('TOO_LONG'))return json(req,{ok:false,code:raw.split(':')[0]},400);console.error(JSON.stringify({level:'error',msg:'crm_api_failed',code:raw.split(':')[0]}));return json(req,{ok:false,code:'CRM_QUERY_FAILED'},500);}});
