import assert from 'node:assert/strict';
import pg from 'pg';
import { PostgresAsaasCheckoutReconciliation } from '../supabase/functions/diretoria-asaas-webhook/checkout-reconciliation.ts';
const { Pool } = pg;
const connectionString=process.env.DATABASE_URL;if(!connectionString)throw new Error('DATABASE_URL_REQUIRED');
const pool=new Pool({connectionString});const recon=new PostgresAsaasCheckoutReconciliation(connectionString);const suffix=Date.now().toString(36);let seedCounter=0;
async function one(sql:string,values:unknown[]=[]){const r=await pool.query(sql,values);return r.rows[0];}
async function seedIntent(input:{session:string;paymentStatus:'pending'|'paid';gatewayId?:string}){
  const seed=(++seedCounter).toString(36);
  const fixture=`${suffix.slice(-8)}-${seed}`;
  const profile=await one(`insert into profiles(display_code,full_name,email_normalized,status) values($1,$2,$3,'active') returning id`,[`CI-A-${fixture}`,'CI Asaas',`ci-a-${fixture}@example.invalid`]);
  const user=await one(`insert into users(profile_id,auth_provider,provider_subject,status) values($1,'system',$2,'active') returning id`,[profile.id,`ci-a-${fixture}`]);
  const event=await one(`insert into events(event_code,name,slug,status,created_by) values($1,$2,$3,'PLANEJAMENTO',$4) returning id`,[`CI-A-${fixture}`,`CI ${input.session}`,`ci-a-${fixture}`,user.id]);
  const config=await one(`insert into event_financial_configs(event_id,version,founder_ticket_gross,estimated_fee_per_member,variable_cost_per_member,contingency_type,contingency_value,approved_exposure_limit,created_by,fee_pass_through) values($1,1,150,0,10,'fixed',0,0,$2,true) returning id`,[event.id,user.id]);
  const intent=await one(`insert into checkout_intents(profile_id,event_id,financial_config_id,provider,provider_session_id,idempotency_key,amount_gross,base_amount,processing_fee_amount,currency_code,payment_method,status) values($1,$2,$3,'asaas',$4,$5,155.13,150,5.13,'BRL','pix','pending') returning id`,[profile.id,event.id,config.id,input.session,`ci-${suffix}-${input.session}`]);
  const payment=await one(`insert into payments(profile_id,event_id,purpose,gateway,gateway_payment_id,idempotency_key,amount_gross,base_amount,processing_fee_passed,provider_fee_actual,amount_net,currency_code,payment_method,status,paid_at,checkout_intent_id) values($1,$2,'club_credit','asaas',$3,$4,155.13,150,5.13,$5,$6,'BRL','pix',$7,$8,$9) returning id`,[profile.id,event.id,input.gatewayId??null,`pay-${suffix}-${input.session}`,input.paymentStatus==='paid'?5.13:null,input.paymentStatus==='paid'?150:null,input.paymentStatus,input.paymentStatus==='paid'?new Date():null,intent.id]);
  return{profile,user,event,config,intent,payment};
}
try{
  const expired=await seedIntent({session:`chk-exp-${suffix}`,paymentStatus:'pending'});
  await pool.query(`update checkout_intents set reconciliation_status='required',provider_error_code='CI_PREVIOUS_UNCERTAINTY' where id=$1`,[expired.intent.id]);
  const webhook={provider:'asaas' as const,providerEventId:`evt-exp-${suffix}`,eventType:'expired' as const,checkoutSessionId:`chk-exp-${suffix}`,checkoutStatus:'EXPIRED',externalReference:expired.intent.id,occurredAt:new Date().toISOString(),signatureVerified:true as const,rawPayloadHash:'a'.repeat(64)};
  const first=await recon.processLifecycle(webhook);assert.equal(first.replayed,false);const expiredIntent=await one(`select status,reconciliation_status,provider_error_code from checkout_intents where id=$1`,[expired.intent.id]);assert.equal(expiredIntent.status,'expired');assert.equal(expiredIntent.reconciliation_status,'resolved');assert.equal(expiredIntent.provider_error_code,'ASAAS_CHECKOUT_EXPIRED_TERMINAL');assert.equal((await one(`select status from payments where id=$1`,[expired.payment.id])).status,'expired');
  const replay=await recon.processLifecycle(webhook);assert.equal(replay.replayed,true);

  const created=await seedIntent({session:`chk-created-${suffix}`,paymentStatus:'pending'});
  const createdWebhook={provider:'asaas' as const,providerEventId:`evt-created-${suffix}`,eventType:'created' as const,checkoutSessionId:`chk-created-${suffix}`,checkoutStatus:'ACTIVE',externalReference:created.intent.id,occurredAt:new Date().toISOString(),signatureVerified:true as const,rawPayloadHash:'c'.repeat(64)};
  const createdFirst=await recon.processLifecycle(createdWebhook);assert.equal(createdFirst.replayed,false);assert.equal(createdFirst.state,'pending');
  const createdReplay=await recon.processLifecycle(createdWebhook);assert.equal(createdReplay.replayed,true);
  const candidateRows=await recon.findUnboundCandidates('155.13','pix');assert.ok(candidateRows.some(row=>row.id===created.intent.id));

  const recovery=await seedIntent({session:`chk-recover-${suffix}`,paymentStatus:'pending'});
  await pool.query(`delete from payments where id=$1`,[recovery.payment.id]);
  const recovered=await recon.ensurePendingPayment(recovery.intent.id);assert.equal(recovered.created,true);
  const recoveredPayment=await one(`select status,checkout_intent_id,amount_gross,base_amount,processing_fee_passed from payments where id=$1`,[recovered.paymentId]);assert.equal(recoveredPayment.status,'pending');assert.equal(recoveredPayment.checkout_intent_id,recovery.intent.id);assert.equal(String(recoveredPayment.amount_gross),'155.13');assert.equal(String(recoveredPayment.base_amount),'150.00');assert.equal(String(recoveredPayment.processing_fee_passed),'5.13');
  const recoveredReplay=await recon.ensurePendingPayment(recovery.intent.id);assert.equal(recoveredReplay.created,false);assert.equal(recoveredReplay.paymentId,recovered.paymentId);
  const recoveryAudit=await one(`select action,reason from audit_logs where entity_type='checkout_intent' and entity_id=$1 and action='checkout.binding_recovered_from_webhook' order by occurred_at desc limit 1`,[recovery.intent.id]);assert.equal(recoveryAudit.reason,'ASAAS_VERIFIED_WEBHOOK_RECOVERY');

  const paid=await seedIntent({session:`chk-paid-${suffix}`,paymentStatus:'paid',gatewayId:`pay-paid-${suffix}`});
  const byProvider=await recon.findIntentByProviderPaymentId(`pay-paid-${suffix}`);assert.equal(byProvider.id,paid.intent.id);
  const refund=await one(`insert into refunds(payment_id,profile_id,event_id,amount,reason,status,requested_by) values($1,$2,$3,155.13,'CI refund','processing',$4) returning id`,[paid.payment.id,paid.profile.id,paid.event.id,paid.user.id]);
  const marked=await recon.markRefundFinal(paid.payment.id);assert.equal(marked.refundId,refund.id);assert.equal(marked.created,false);assert.equal((await one(`select status from refunds where id=$1`,[refund.id])).status,'paid');

  const external=await seedIntent({session:`chk-ext-${suffix}`,paymentStatus:'paid',gatewayId:`pay-ext-${suffix}`});
  const ext=await recon.markRefundFinal(external.payment.id);assert.equal(ext.created,true);const extRow=await one(`select status,reason,amount from refunds where id=$1`,[ext.refundId]);assert.equal(extRow.status,'paid');assert.equal(extRow.reason,'ASAAS_WEBHOOK_EXTERNAL_REFUND');assert.equal(String(extRow.amount),'155.13');

  const progress=await seedIntent({session:`chk-progress-${suffix}`,paymentStatus:'paid',gatewayId:`pay-progress-${suffix}`});
  const progressTracked=await recon.recordRefundProgress({providerEventId:`evt-refund-progress-${suffix}`,providerPaymentId:`pay-progress-${suffix}`,rawPayloadHash:'e'.repeat(64)});assert.equal(progressTracked.replayed,false);assert.ok(progressTracked.refundId);const progressRefund=await one(`select status,reason from refunds where id=$1`,[progressTracked.refundId]);assert.equal(progressRefund.status,'processing');assert.equal(progressRefund.reason,'ASAAS_WEBHOOK_EXTERNAL_REFUND_IN_PROGRESS');const progressPayment=await one(`select status from payments where id=$1`,[progress.payment.id]);assert.equal(progressPayment.status,'paid');const progressReplay=await recon.recordRefundProgress({providerEventId:`evt-refund-progress-${suffix}`,providerPaymentId:`pay-progress-${suffix}`,rawPayloadHash:'e'.repeat(64)});assert.equal(progressReplay.replayed,true);

  await pool.query(`update checkout_intents set reconciliation_status='required',provider_error_code='REFUND_RECONCILIATION_REQUIRED_ASAAS_REQUEST_TIMEOUT' where id=$1`,[progress.intent.id]);
  const denied=await recon.recordRefundDenied({providerEventId:`evt-refund-denied-${suffix}`,providerPaymentId:`pay-progress-${suffix}`,rawPayloadHash:'f'.repeat(64)});assert.equal(denied.replayed,false);assert.equal(denied.refundId,progressTracked.refundId);const deniedRefund=await one(`select status from refunds where id=$1`,[denied.refundId]);assert.equal(deniedRefund.status,'failed');assert.equal((await one(`select status from payments where id=$1`,[progress.payment.id])).status,'paid');const deniedIntent=await one(`select reconciliation_status,provider_error_code from checkout_intents where id=$1`,[progress.intent.id]);assert.equal(deniedIntent.reconciliation_status,'resolved');assert.equal(deniedIntent.provider_error_code,'ASAAS_REFUND_DENIED_TERMINAL');const deniedReplay=await recon.recordRefundDenied({providerEventId:`evt-refund-denied-${suffix}`,providerPaymentId:`pay-progress-${suffix}`,rawPayloadHash:'f'.repeat(64)});assert.equal(deniedReplay.replayed,true);

  const finalRecon=await seedIntent({session:`chk-refinal-${suffix}`,paymentStatus:'paid',gatewayId:`pay-refinal-${suffix}`});
  await one(`insert into refunds(payment_id,profile_id,event_id,amount,reason,status,requested_by) values($1,$2,$3,155.13,'CI ambiguous refund','processing',$4) returning id`,[finalRecon.payment.id,finalRecon.profile.id,finalRecon.event.id,finalRecon.user.id]);await pool.query(`update checkout_intents set reconciliation_status='required',provider_error_code='REFUND_RECONCILIATION_REQUIRED_ASAAS_NETWORK_ERROR' where id=$1`,[finalRecon.intent.id]);await recon.markRefundFinal(finalRecon.payment.id);const finalIntent=await one(`select reconciliation_status,provider_error_code from checkout_intents where id=$1`,[finalRecon.intent.id]);assert.equal(finalIntent.reconciliation_status,'resolved');assert.equal(finalIntent.provider_error_code,'ASAAS_REFUND_PAID_TERMINAL');

  const mismatch=await recon.recordVerifiedPaymentReconciliation({providerEventId:`evt-mismatch-${suffix}`,providerPaymentId:`pay-paid-${suffix}`,checkoutIntentId:paid.intent.id,rawPayloadHash:'d'.repeat(64),code:'PAYMENT_WEBHOOK_AMOUNT_MISMATCH'});assert.equal(mismatch.replayed,false);const mismatchIntent=await one(`select reconciliation_status,provider_error_code from checkout_intents where id=$1`,[paid.intent.id]);assert.equal(mismatchIntent.reconciliation_status,'required');assert.equal(mismatchIntent.provider_error_code,'PAYMENT_WEBHOOK_AMOUNT_MISMATCH');const mismatchReceipt=await one(`select processing_status,error_message from payment_webhook_receipts where gateway='asaas' and gateway_event_id=$1`,[`evt-mismatch-${suffix}`]);assert.equal(mismatchReceipt.processing_status,'failed');assert.equal(mismatchReceipt.error_message,'PAYMENT_WEBHOOK_AMOUNT_MISMATCH');const mismatchReplay=await recon.recordVerifiedPaymentReconciliation({providerEventId:`evt-mismatch-${suffix}`,providerPaymentId:`pay-paid-${suffix}`,checkoutIntentId:paid.intent.id,rawPayloadHash:'d'.repeat(64),code:'PAYMENT_WEBHOOK_AMOUNT_MISMATCH'});assert.equal(mismatchReplay.replayed,true);

  const partial=await recon.recordPartialRefundReconciliation({providerEventId:`evt-part-${suffix}`,providerPaymentId:`pay-paid-${suffix}`,rawPayloadHash:'b'.repeat(64)});assert.equal(partial.replayed,false);const partialIntent=await one(`select reconciliation_status,provider_error_code from checkout_intents where id=$1`,[paid.intent.id]);assert.equal(partialIntent.reconciliation_status,'required');assert.equal(partialIntent.provider_error_code,'ASAAS_PARTIAL_REFUND_RECONCILIATION_REQUIRED');const partialReceipt=await one(`select processing_status,error_message from payment_webhook_receipts where gateway='asaas' and gateway_event_id=$1`,[`evt-part-${suffix}`]);assert.equal(partialReceipt.processing_status,'failed');
  const partialReplay=await recon.recordPartialRefundReconciliation({providerEventId:`evt-part-${suffix}`,providerPaymentId:`pay-paid-${suffix}`,rawPayloadHash:'b'.repeat(64)});assert.equal(partialReplay.replayed,true);
  console.log('OK: Asaas HML V3 PostgreSQL reconciliation/refund integration');
}finally{await recon.close();await pool.end();}
